### ISSUE TITLE
How does one get an attachment with settee?

### ISSUE THREAD

**Issue by mtedesco** [inadarei/settee#1]

**Comment by inadarei** [comment]
When you load a document, all attachments on that document get loaded into the ['_attachments'] array of the loaded $doc object.

**Comment by mtedesco** [comment]
Thank you for the reply, but I'm still stuck... I can easily see that the data about the attachment (like mime type) in _attachments, but I am unable to retrieve the binary attachment itself.   Please advise.

Thank you again for replying.  
Mike
